"""change strategy schema

Revision ID: 502a00918104
Revises: 5d27add23bd9
Create Date: 2022-01-24 19:28:55.504483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '502a00918104'
down_revision = '5d27add23bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('solution', sa.VARCHAR(), nullable=True))
    op.add_column('strategy', sa.Column('timestamp', sa.TIMESTAMP(), nullable=False))
    op.drop_column('strategy', 'meta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('strategy', 'timestamp')
    op.drop_column('strategy', 'solution')
    # ### end Alembic commands ###
