"""change strategy schema

Revision ID: 5d27add23bd9
Revises: 6de628e8633e
Create Date: 2022-01-24 16:35:49.158600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d27add23bd9'
down_revision = '6de628e8633e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('type', sa.VARCHAR(), nullable=True))
    op.add_column('strategy', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('strategy_sensor_id_fkey', 'strategy', type_='foreignkey')
    op.drop_column('strategy', 'action')
    op.drop_column('strategy', 'sensor_id')
    # ### end Alembic commands ###

    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('sensor_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('strategy', sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_foreign_key('strategy_sensor_id_fkey', 'strategy', 'sensor', ['sensor_id'], ['id'])
    op.drop_column('strategy', 'meta')
    op.drop_column('strategy', 'type')
    # ### end Alembic commands ###
