"""Added Smart Meter

Revision ID: 6de628e8633e
Revises: c41bea07f448
Create Date: 2022-01-23 01:57:29.008838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6de628e8633e'
down_revision = 'c41bea07f448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'strategy',
        sa.Column('schedule_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('pattern', postgresql.ARRAY(sa.FLOAT()), nullable=False),
        sa.Column('sensor_id', sa.VARCHAR(), nullable=False),
        sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
        sa.PrimaryKeyConstraint('schedule_id', 'sensor_id', 'action'),
        sa.UniqueConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy')
    # ### end Alembic commands ###
