"""Added Smart Meter

Revision ID: c41bea07f448
Revises: 1969c8a373a2
Create Date: 2022-01-23 01:56:12.370596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c41bea07f448'
down_revision = '1969c8a373a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'smart_meter',
        sa.Column('id', sa.VARCHAR(), nullable=False),
        sa.Column('time', sa.TIMESTAMP(), nullable=False),
        sa.Column('energy', postgresql.DOUBLE_PRECISION(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['sensor.id'], ),
        sa.PrimaryKeyConstraint('id', 'time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smart_meter')
    # ### end Alembic commands ###
